# Site settings
title: Parfait
email: fredrik@parfait.se
description: > # this means to ignore newlines until "baseurl:"

  This site is about Parfait74 and his education, work and hobbies. Besides working
  at CSC in Stockholm as a Solution Architect he is is also attending a
  program at Linné University called "Utveckling och drift av mjukvarubaserade system".

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: parfait74
github_username:  parfait74

# Build settings
markdown: kramdown
